[project]
name = "storywriter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "elevenlabs-mcp>=0.9.0",
    "pdfplumber>=0.11.8",
    "pypdf>=6.5.0",
]
